[build.environment]
  YARN_VERSION = "1.22.10"
  NPM_VERSION = "8.5.0"
  HUGO_VERSION = "0.98.0"
  NODE_VERSION = "16.14.2"
  HUGO_ENABLEGITINFO = "true"

[functions]
    directory = "functions"

[build]
  HUGO_ENV = "production"
  command = "yarn build"
  publish = "dist"

[context.deploy-preview]
  command = "yarn build:preview"

[context.production.environment]
  HUGO_ENV = "production"


[[headers]]
  for = "/images/*"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "/uploads/*"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.jpg"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.css"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.js"
  [headers.values]
    	cache-control = "public, max-age=31536000, immutable"
[[headers]]
  for = "*.html"
  [headers.values]
    cache-control = '''
    max-age=0,
    no-cache,
    no-store,
    must-revalidate'''
#[[plugins]]
#   package = "netlify-plugin-image-optim"
[[plugins]]
  package = "netlify-plugin-hugo-cache-resources"
	[plugins.inputs]
	# If it should show more verbose logs (optional, default = true)
    srcdir = "site"
	debug = false
[[plugins]]
    package = "netlify-plugin-submit-sitemap"
        [plugins.inputs]
        # The base url of your site (optional, default = main URL set in Netlify)
        baseUrl = "https://www.playmob.com"

        # Path to the sitemap URL (optional, default = /sitemap.xml)
        sitemapPath = "/sitemap.xml"

        # Enabled providers to submit sitemap to (optional, default = 'google', 'bing', 'yandex'). Possible providers are currently only 'google', 'bing', 'yandex'.
        providers = [
            "google",
            "bing",
            "yandex"
        ]

